#!/bin/sh
# VAL_DATA should refer to the directory in which VALHALLA data files are placed.
#VAL_DATA=~/valhalla
#VAL_DATA=/usr/local/valhalla
VAL_DATA=.

# VAL_BIN should refer to the directory in which VALHALLA executable files are placed.
VAL_BIN=${VAL_DATA}/bin/bin_unix

# VAL_OPTIONS contains any command line options you would like to start VALHALLA with.
#VAL_OPTIONS=""
VAL_OPTIONS="-u${HOME}/.valhalla/v1.0.0-beta.2"

# SYSTEM_NAME should be set to the name of your operating system.
#SYSTEM_NAME=Linux
SYSTEM_NAME=`uname -s`

# MACHINE_NAME should be set to the name of your processor.
#MACHINE_NAME=i686
MACHINE_NAME=`uname -m`

case ${SYSTEM_NAME} in
Linux)
  SYSTEM_NAME=linux_
  ;;
*)
  SYSTEM_NAME=unknown_
  ;;
esac

case ${MACHINE_NAME} in
i486|i586|i686)
  MACHINE_NAME=
  ;;
x86_64|amd64)
  MACHINE_NAME=64_
  ;;
*)
  if [ ${SYSTEM_NAME} != native_ ]
  then
    SYSTEM_NAME=native_
  fi
  MACHINE_NAME=
  ;;
esac

if [ -x ${VAL_BIN}/native_client ]
then
  SYSTEM_NAME=native_
  MACHINE_NAME=
fi

if [ -x ${VAL_BIN}/${SYSTEM_NAME}${MACHINE_NAME}client ]
then
  cd ${VAL_DATA}
  exec ${VAL_BIN}/${SYSTEM_NAME}${MACHINE_NAME}client ${VAL_OPTIONS} "$@"
else
  echo "Your platform does not have a pre-compiled Valhalla client."
  echo "Please follow the following steps to build a native client:"
  echo "1) Ensure you have the SDL2, SDL2-image, SDL2-mixer, and OpenGL libraries installed."
  echo "2) Type \"make -C source install\"."
  echo "3) If the build succeeds, run this script again."
  exit 1
fi

